name: Repackage UOS/Deepin packages

on:
  workflow_dispatch:

env:
  REPOSITORY_URL: "https://home-store-packages.uniontech.com/appstore"
  REPOSITORY_DIST: "eagle"

jobs:
  download_package:
    runs-on: ubuntu-latest
    steps:
    - name: Download Release file
      run: |
        # Download the Release file
        curl -fsL -o Release "${{ env.REPOSITORY_URL }}/dists/${{ env.REPOSITORY_DIST }}/Release"
        
    - name: Parse package sources
      run: |
        grep -Eo '[^ ]+/Packages' Release | sort | uniq > package.sources
        
    - name: Download package sources
      run: |
        while read source; do
          echo "Downloading package source: ${source}"
          curl -sL -O "${{ env.REPOSITORY_URL }}/dists/${{ env.REPOSITORY_DIST }}/${source}"
        done < package.sources > Packages
    
    - name: Download packages
      run: |
        while read -r package; do
          echo "Downloading package: ${package}"
          curl -sL -o $(basename "${package}") "${{ env.REPOSITORY_URL }}/${package}"
        done < <(grep -oE '[^ ]+com\.cvte\.exceedshare[^ ]+\.deb' Packages)
    
    - name: Upload debian packages
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: '*.deb'
        overwrite: true
