name: Repackage UOS/Deepin packages

on:
  workflow_dispatch:
    inputs:
      ignore_existing:
        description: 'Ignore existing releases'
        required: true
        type: 'boolean'
        default: 'true'
      download_existing:
        description: 'Download instead of building'
        required: true
        type: 'boolean'
        default: 'false'
  schedule:
    - cron: "0 0 * * *"

env:
  PERMANENT_RELEASE: latest
  REPOSITORY_URL: "https://home-store-packages.uniontech.com/appstore"
  REPOSITORY_DIST: "eagle"
  PACKAGE_NAME: com.cvte.exceedshare

jobs:
  download-lists:
    name: Find latest packages
    runs-on: ubuntu-latest
    outputs:
      items: ${{ steps.items.outputs.items }}
    steps:
    - name: Download Release file
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 5
        command: curl -fL -o Release "${{ env.REPOSITORY_URL }}/dists/${{ env.REPOSITORY_DIST }}/Release"
        
    - name: Parse package sources
      run: |
        grep -Eo '[^ ]+/Packages' Release | sort | uniq > Sources
        [ -s "Sources"] && ( echo "Sources not found" >&2; exit 1 )
        echo "Found sources:"
        cat Sources
        
    - name: Download package sources
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 5
        command: curl -L --parallel --parallel-immediate $(sed -e 's!^!${{ env.REPOSITORY_URL }}/dists/${{ env.REPOSITORY_DIST }}/!g' Sources) > Packages

    - name: Store package items
      id: items
      run: |
        # Capture the output of the grep command
        DEB_LINKS=$(grep -oE '[^ ]+${{ env.PACKAGE_NAME }}[^ ]+\.deb' Packages | sort | uniq)

        # Convert the output to a JSON array
        DEB_LINKS_JSON=$(echo "$DEB_LINKS" | jq -R -s -c 'split("\n") | map(select(length > 0) | {path: ., file: (split("/") | last)})')

        echo $DEB_LINKS_JSON
        # Set the output
        echo "items=$DEB_LINKS_JSON" >> $GITHUB_OUTPUT


  handle-package:
    name: "Rebuild: ${{ matrix.item.file }}"
    runs-on: ubuntu-latest
    needs: download-lists
    strategy:
      matrix:
        item: ${{ fromJSON(needs.download-lists.outputs.items) }}
      fail-fast: false
    steps:
    - name: Store outputs
      id: vars
      run: |
        version="$(echo "${{ matrix.item.file }}" | rev | cut -d'_' -f2 | rev)"
        (
          echo "version=${version}"
          echo "tag=${{ env.PACKAGE_NAME }}-${version}"
          echo "artifact=file-$(echo "${{ matrix.item.file }}" | sha256sum | cut -d' ' -f1)"
        ) >> $GITHUB_OUTPUT

    - name: Check if release upload already exists
      id: check
      run: |
        url="${{ github.server_url }}/${{ github.repository }}/releases/download/${{ steps.vars.outputs.tag }}/${{ matrix.item.file }}"
        echo "url=${url}" >> $GITHUB_OUTPUT

        if curl -fLIZ "${url}" "${url}.sha256"; then
          echo "Release already exists and is uploaded"
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "Release does not exist or is incomplete"
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Download instead of building
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ignore_existing == 'false' && github.event.inputs.download_existing != 'false' && steps.check.outputs.exists == 'true' }}
      id: latest
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 5
        command: |
          curl -fL -o "${{ matrix.item.file }}" "${{ steps.check.outputs.url }}" && touch "${{ matrix.item.file }}.downloaded"

    - name: Download package from repository
      if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.ignore_existing != 'false') || steps.check.outputs.exists == 'false' }}
      id: download
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 5
        command: curl -fL -o "${{ matrix.item.file }}" "${{ env.REPOSITORY_URL }}/${{ matrix.item.path }}"

    - name: Rebuild package
      id: rebuild
      if: ${{ steps.download.outcome == 'success' }}
      run: |
        echo "::group::Extract package contents to a temporary directory"
        mkdir -p unpacked
        dpkg-deb -x "${{ matrix.item.file }}" unpacked
        dpkg-deb --control "${{ matrix.item.file }}" "unpacked/DEBIAN"
        echo "::endgroup::"
        
        echo "::group::Modify package contents"
        # Remove obscure dependency
        if grep -q 'deepin-elf-verify' unpacked/DEBIAN/control; then
          echo "Removing deepin-elf-verify dependency"
          sed -i '/deepin-elf-verify/d' unpacked/DEBIAN/control
        fi
        
        # Make desktop shortcut and icons
        (
            cd "unpacked/opt/apps/${{ env.PACKAGE_NAME }}/entries"
            find applications icons \
                -type f \
                -exec sh -c 'mkdir -p "unpacked/usr/share/$(dirname "{}")"' \; \
                -exec echo 'Symlinking /usr/share/{} to /opt/apps/${{ env.PACKAGE_NAME }}/{}' \; \
                -exec ln -s "/opt/apps/${{ env.PACKAGE_NAME }}/entries/{}" "unpacked/usr/share/{}" \;
        )
        
        # Check if update-desktop-database trigger is present
        if ! grep -q 'update-desktop-database' "unpacked/DEBIAN/postinst"; then
            echo "Adding trigger to update desktop links database"
            echo 'dpkg-trigger update-desktop-database' >> "unpacked/DEBIAN/postinst"
        fi
        echo "::endgroup::"
        
        echo "::group::Prepare output files"
        dpkg -b unpacked "${{ matrix.item.file }}"
        echo "::endgroup::"

    - name: Upload artifacts
      if: ${{ steps.download.outcome == 'success' || steps.latest.outcome == 'success' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.vars.outputs.artifact }}
        path: "${{ matrix.item.file }}*"


  define-upload-matrix:
    name: Define release versions
    runs-on: ubuntu-latest
    needs: handle-package
    outputs:
      versions: ${{ steps.extract.outputs.versions }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List .deb files and extract versions
        id: extract
        run: |
          mkdir -p release
          release() {
            echo "::group::Copy $1 to release/$2/$3"
            mkdir -p "release/$2"
            cp "$1" "release/$2/$3"
            (cd "release/$2" && sha256sum "$3" > "$3.sha256")
            echo "::endgroup::"
          }
          for file in $(find artifacts -name "*.deb"); do
            # Extract the version using basename and cut
            filename=$(basename "$file")
            version="$(echo "$filename" | rev | cut -d'_' -f2 | rev)"

            # Release version only if not downloaded already
            if [ ! -e "${file}.downloaded" ]; then
              release "$file" "$version" "$filename"
            fi

            # Release latest regardless
            release "$file" "${{ env.PERMANENT_RELEASE }}" "${filename/_${version}_/_latest_}"
          done
          echo "versions=$(ls release | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: ${{ steps.extract.outputs.versions != '[]' }}
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release
  

  upload-release:
    runs-on: ubuntu-latest
    needs: define-upload-matrix
    name: Release ${{ matrix.version }} packages
    strategy:
      matrix:
        version: ${{ fromJSON(needs.define-upload-matrix.outputs.versions) }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: release
          path: release

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.PACKAGE_NAME }}-${{ matrix.version }}"
          files: "release/${{ matrix.version }}/*"
          make_latest: ${{ matrix.version == env.PERMANENT_RELEASE }}
          prerelease: ${{ matrix.version != env.PERMANENT_RELEASE }}


  create-repository:
    runs-on: ubuntu-latest
    needs: upload-release
    name: Update APT repository
    steps:
      - name: Checkout signing key
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: release
          sparse-checkout: 'signing-key.pub'
          sparse-checkout-cone-mode: false
        
      - name: Download latest versions
        uses: robinraju/release-downloader@main
        with:
          tag: ${{ env.PACKAGE_NAME }}-${{ env.PERMANENT_RELEASE }}
          fileName: '*.deb'
          tarBall: false
          zipBall: false
          out-file-path: release
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare data
        id: data
        run: |
          echo "architectures<<EOF" >> $GITHUB_OUTPUT
          for file in release/*.deb; do
              echo "$file" | rev | cut -d'_' -f1 | rev
          done | sort | uniq >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "public<<EOF" >> $GITHUB_OUTPUT
          cat release/public.key >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
      - uses: smeinecke/apt-repo-action@v2.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: ${{ steps.data.outputs.architectures }}
          repo_supported_version: debian
          file: "release/*.deb"
          file_target_version: debian
          public_key: ${{ steps.data.outputs.public }}
          private_key: ${{ secrets.REPO_PRIVATE }}
          key_passphrase: ${{ secrets.REPO_SECRET }}
